### ISSUE TITLE
Not yet available on rubygems

### ISSUE THREAD

**Issue by snowblink** [ci-reporter/ci_reporter_rspec#1]

**Comment by shepmaster** [comment]
Sorry for the confusion - I changed the master branch of ci_reporter, but forgot to point out that this is part of the work for ci_reporter 2.0. If you wish to use ci_reporter right now, you are better off using the 1.9 branch. If you are interested in beta testing the 2.0 support, let us know and we can work something out.

**Comment by shepmaster** [comment]
But it is [now available](https://rubygems.org/gems/ci_reporter_rspec) as a prerelease! :smile_cat:
