### ISSUE TITLE
Add support for rspec 3.4

### ISSUE THREAD

**Issue by claptimes5** [ci-reporter/ci_reporter_rspec#16]
https://github.com/rspec/rspec/releases/tag/v3.4.0

**Comment by shepmaster** [comment]
Any pointers to what doesn't work with 3.4? The gem spec seems to indicate that 3.4 is supported. I'm away from a computer at the moment, so I can't test right this second.

**Comment by claptimes5** [comment]
When I ran bundler, it says the dependencies didn't match up. I'll double
check tomorrow and post the message!

**Comment by claptimes5** [comment]
Looks like the issue was on my end and how the gem depencies were being updated. Thanks for looking into it!
